spring:
  application:
    name: SpringPrj

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_3_spring_prj?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB


#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
